### ISSUE TITLE
Claiming plots fails with bordering

### ISSUE THREAD

**Issue by HaedHutner** [Atherys-Horizons/AtherysTowns#52]
**Description**:
Cannot claim plots because of bordering check issues.

**Expected Behavior**:
When a new plot is selected such that it borders and already-existing town plot, it should be claimed if it meets the remaining requirements for plot claiming.

**Observed Behavior**:
The bordering plot selection cannot be claimed, and fails with the following error:
![image](https://user-images.githubusercontent.com/26813594/55333864-c5b53b00-54a0-11e9-97ca-522f5912e0ad.png)

**Comment by LJNIC** [comment]
Can you explain how you managed to try and claim a plot? I just throw NullPointerExceptions when attempting `/town claim` inside a selection. Relevant log:
```
Error occurred while executing command 'town claim' for source EntityPlayerMP['Rynelf'/4938, l='world', x=850.14, y=97.28, z=-383.93]: null
java.lang.NullPointerException: null
at com.atherys.towns.service.PermissionService.formatSubjectId(PermissionService.java:145) ~[PermissionService.class:?]
at com.atherys.towns.service.PermissionService.isPermitted(PermissionService.java:101) ~[PermissionService.class:?]
at com.atherys.towns.facade.PermissionFacade.isPermitted(PermissionFacade.java:46) ~[PermissionFacade.class:?]
at com.atherys.towns.facade.TownFacade.claimTownPlotFromPlayerSelection(TownFacade.java:184) ~[TownFacade.class:?]
at com.atherys.towns.command.town.ClaimPlotCommand.execute(ClaimPlotCommand.java:19) ~[ClaimPlotCommand.class:?]
at com.atherys.core.command.PlayerCommand.execute(PlayerCommand.java:21) ~[PlayerCommand.class:?] 
```

**Comment by HaedHutner** [comment]
This is blocked by #53
